language: php

php:
  - 5.4
  - 5.5
  - 5.6

group: stable

env:
  - PHALCON_VERSION="2.1.x"
  - PHALCON_VERSION="phalcon-v2.0.10"

before_install:
  - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b ${PHALCON_VERSION}
  - (cd cphalcon/ext; export CFLAGS="-g0 -O0 -std=gnu90"; phpize &> /dev/null && ./configure --silent --enable-phalcon &> /dev/null && make --silent -j2 &> /dev/null && make --silent install)
  - phpenv config-add tests/_ci/phalcon.ini &> /dev/null
  - php --ri phalcon
  - travis_retry composer self-update -q
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - travis_retry composer install --prefer-dist --no-interaction
  - ulimit -c unlimited -S || true
  - stty cols 160

script:
  - vendor/bin/phpcs --standard=PSR2 --colors --extensions=php --encoding=utf-8 src/

notifications:
  email:
    recipients:
      - serghei@phalconphp.com
    on_success: change
    on_failure: always

addons:
  apt:
    packages:
      - gdb
